### Persons
GET {{baseUrl}}/persons/
Accept: application/json

###
@person_id = 36
GET {{baseUrl}}/persons/{{person_id}}

###
POST {{baseUrl}}/persons
Content-Type: application/json
Accept: application/json

{
  "firstName": "Mohamed",
  "lastName": "BENIANE",
  "email": "benianus3d@gmail.com",
  "phone": "+213658854637",
  "address": "city 36",
  "birthdate": "1994-02-11"
}

###
@person_u_id = 36
PUT {{baseUrl}}/persons/{{person_u_id}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "Mohasdsmed",
  "lastName": "BENIAsdsNE",
  "email": "benianuss3d@gmail.com",
  "phone": "+213658854636",
  "address": "city 36",
  "birthdate": "1994-02-11"
}

###
@person_d_id = 36
DELETE {{baseUrl}}/persons/{{person_d_id}}

